version: '3.8'

services:
  postgres:
    env_file:
      - postgresql.env
    restart: always
    image: postgres:15
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app
  rabbitmq-server:
    image: "rabbitmq:3.6-management-alpine"
    hostname: "rabbitmq-host"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "pass"
    networks:
      - rabbitnetwork
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 5s
      retries: 3
  image-processing-api:
    env_file:
      - postgresql.env
      - image-processing-api/rabbitmq.env
    build: ./image-processing-api
    ports:
      - 5050:5050
      - 7000:7000
    volumes:
      - ./src:/src
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq-server:
        condition: service_healthy
    environment:
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSWORD: pass
      RABBITMQ_HOST: rabbitmq-server
      RABBITMQ_QUEUE: dataqueue
      RABBITMQ_ROUTING_KEY: dataqueue 
      RABBITMQ_EXCHANGE: exchange_test
    command: python app.py
    networks:
      - rabbitnetwork
      - app
  worker:
    env_file:
      - postgresql.env
      - image-processing-api/rabbitmq.env
    build: .
    volumes:
      - ./src:/src
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq-server:
        condition: service_healthy
    environment:
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSWORD: pass
      RABBITMQ_HOST: rabbitmq-server
      RABBITMQ_QUEUE: dataqueue
      RABBITMQ_ROUTING_KEY: dataqueue 
      RABBITMQ_EXCHANGE: exchange_test
    command: python scripts/worker.py
    networks:
      - rabbitnetwork
      - app
    deploy:
      mode: replicated
      replicas: 2